// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetVenuesData, GetVenuesResponse, GetTeamsData, GetTeamsResponse, GetTeamRosterData, GetTeamRosterResponse, GetSubstitutionsByGameData, GetSubstitutionsByGameResponse, GetSubstitutionsByPlayerIdData, GetSubstitutionsByPlayerIdResponse, GetSubstitutionsByTeamData, GetSubstitutionsByTeamResponse, GetTeamLeaderboardStatsData, GetTeamLeaderboardStatsResponse, GetTeamSeasonStatsData, GetTeamSeasonStatsResponse, GetTeamSeasonShootingStatsData, GetTeamSeasonShootingStatsResponse, GetPlayerSeasonStatsData, GetPlayerSeasonStatsResponse, GetPlayerSeasonShootingStatsData, GetPlayerSeasonShootingStatsResponse, GetRecruitsData, GetRecruitsResponse, GetTeamRecruitingRankingsData, GetTeamRecruitingRankingsResponse, GetPortalTransfersData, GetPortalTransfersResponse, GetSrsData, GetSrsResponse, GetAdjustedEfficiencyData, GetAdjustedEfficiencyResponse, GetEloData, GetEloResponse, GetRankingsData, GetRankingsResponse, GetPlaysData, GetPlaysResponse, GetPlaysByPlayerIdData, GetPlaysByPlayerIdResponse, GetPlaysByTeamData, GetPlaysByTeamResponse, GetPlaysByDateData, GetPlaysByDateResponse, GetPlaysByTournamentData, GetPlaysByTournamentResponse, GetPlayTypesData, GetPlayTypesResponse, GetLineupsByTeamSeasonData, GetLineupsByTeamSeasonResponse, GetLineupStatsByGameData, GetLineupStatsByGameResponse, GetLinesData, GetLinesResponse, GetProvidersData, GetProvidersResponse, GetGamesData, GetGamesResponse, GetBroadcastsData, GetBroadcastsResponse, GetGameTeamsData, GetGameTeamsResponse, GetGamePlayersData, GetGamePlayersResponse, GetScoreboardData, GetScoreboardResponse, GetDraftTeamsData, GetDraftTeamsResponse, GetDraftPositionsData, GetDraftPositionsResponse, GetDraftPicksData, GetDraftPicksResponse, GetConferencesData, GetConferencesResponse, GetConferenceHistoryData, GetConferenceHistoryResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
};

/**
 * Returns available venues and location information.
 */
export const getVenues = <ThrowOnError extends boolean = false>(options?: Options<GetVenuesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetVenuesResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/venues',
        ...options
    });
};

/**
 * Returns team and conference information.
 */
export const getTeams = <ThrowOnError extends boolean = false>(options?: Options<GetTeamsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTeamsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/teams',
        ...options
    });
};

/**
 * Returns team rosters for a season.
 */
export const getTeamRoster = <ThrowOnError extends boolean = false>(options: Options<GetTeamRosterData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTeamRosterResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/teams/roster',
        ...options
    });
};

/**
 * Returns all recorded player substitutions for a game.
 */
export const getSubstitutionsByGame = <ThrowOnError extends boolean = false>(options: Options<GetSubstitutionsByGameData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSubstitutionsByGameResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/substitutions/game/{gameId}',
        ...options
    });
};

/**
 * Returns all recorded player substitutions for a player and season.
 */
export const getSubstitutionsByPlayerId = <ThrowOnError extends boolean = false>(options: Options<GetSubstitutionsByPlayerIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSubstitutionsByPlayerIdResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/substitutions/player/{playerId}',
        ...options
    });
};

/**
 * Returns all recorded player substitutions for a team and season.
 */
export const getSubstitutionsByTeam = <ThrowOnError extends boolean = false>(options: Options<GetSubstitutionsByTeamData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSubstitutionsByTeamResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/substitutions/team',
        ...options
    });
};

/**
 * Returns team leaderboard statistics. This endpoint requires Patreon Tier 2 access or higher.
 */
export const getTeamLeaderboardStats = <ThrowOnError extends boolean = false>(options?: Options<GetTeamLeaderboardStatsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTeamLeaderboardStatsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/stats/team/leaderboard',
        ...options
    });
};

/**
 * Returns team season statistics. Provide at least a season or team.
 */
export const getTeamSeasonStats = <ThrowOnError extends boolean = false>(options?: Options<GetTeamSeasonStatsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTeamSeasonStatsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/stats/team/season',
        ...options
    });
};

/**
 * Returns team shooting statistics for a season. Provide a team or conference.
 */
export const getTeamSeasonShootingStats = <ThrowOnError extends boolean = false>(options: Options<GetTeamSeasonShootingStatsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTeamSeasonShootingStatsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/stats/team/shooting/season',
        ...options
    });
};

/**
 * Returns player statistics for a season.
 */
export const getPlayerSeasonStats = <ThrowOnError extends boolean = false>(options: Options<GetPlayerSeasonStatsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPlayerSeasonStatsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/stats/player/season',
        ...options
    });
};

/**
 * Returns player shooting statistics for a season. Provide a team or conference.
 */
export const getPlayerSeasonShootingStats = <ThrowOnError extends boolean = false>(options: Options<GetPlayerSeasonShootingStatsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPlayerSeasonShootingStatsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/stats/player/shooting/season',
        ...options
    });
};

/**
 * Returns historical composite player recruiting rankings and ratings.
 */
export const getRecruits = <ThrowOnError extends boolean = false>(options?: Options<GetRecruitsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRecruitsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/recruiting/players',
        ...options
    });
};

/**
 * Returns historical composite team recruiting rankings.
 */
export const getTeamRecruitingRankings = <ThrowOnError extends boolean = false>(options?: Options<GetTeamRecruitingRankingsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTeamRecruitingRankingsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/recruiting/teams',
        ...options
    });
};

/**
 * Returns historical transfer portal activity.
 */
export const getPortalTransfers = <ThrowOnError extends boolean = false>(options?: Options<GetPortalTransfersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetPortalTransfersResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/recruiting/portal',
        ...options
    });
};

/**
 * Returns Simple Rating System (SRS) ratings.
 */
export const getSrs = <ThrowOnError extends boolean = false>(options?: Options<GetSrsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSrsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/ratings/srs',
        ...options
    });
};

/**
 * Returns adjusted offensive and defensive efficiency ratings.
 */
export const getAdjustedEfficiency = <ThrowOnError extends boolean = false>(options?: Options<GetAdjustedEfficiencyData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAdjustedEfficiencyResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/ratings/adjusted',
        ...options
    });
};

/**
 * Returns historical Elo ratings.
 */
export const getElo = <ThrowOnError extends boolean = false>(options?: Options<GetEloData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetEloResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/ratings/elo',
        ...options
    });
};

/**
 * Returns historical poll rankings.
 */
export const getRankings = <ThrowOnError extends boolean = false>(options?: Options<GetRankingsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRankingsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/rankings',
        ...options
    });
};

/**
 * Returns all recorded plays for a game.
 */
export const getPlays = <ThrowOnError extends boolean = false>(options: Options<GetPlaysData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPlaysResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/plays/game/{gameId}',
        ...options
    });
};

/**
 * Returns all recorded plays for a player and season.
 */
export const getPlaysByPlayerId = <ThrowOnError extends boolean = false>(options: Options<GetPlaysByPlayerIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPlaysByPlayerIdResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/plays/player/{playerId}',
        ...options
    });
};

/**
 * Returns all recorded plays for a team and season.
 */
export const getPlaysByTeam = <ThrowOnError extends boolean = false>(options: Options<GetPlaysByTeamData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPlaysByTeamResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/plays/team',
        ...options
    });
};

/**
 * Returns all recorded plays for a UTC date.
 */
export const getPlaysByDate = <ThrowOnError extends boolean = false>(options: Options<GetPlaysByDateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPlaysByDateResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/plays/date',
        ...options
    });
};

/**
 * Returns all recorded plays for a tournament and season.
 */
export const getPlaysByTournament = <ThrowOnError extends boolean = false>(options: Options<GetPlaysByTournamentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPlaysByTournamentResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/plays/tournament',
        ...options
    });
};

/**
 * Returns available play types and their identifiers.
 */
export const getPlayTypes = <ThrowOnError extends boolean = false>(options?: Options<GetPlayTypesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetPlayTypesResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/plays/types',
        ...options
    });
};

/**
 * Returns lineup statistics for a team and season.
 */
export const getLineupsByTeamSeason = <ThrowOnError extends boolean = false>(options: Options<GetLineupsByTeamSeasonData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetLineupsByTeamSeasonResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/lineups/team',
        ...options
    });
};

/**
 * Returns lineup statistics for a game.
 */
export const getLineupStatsByGame = <ThrowOnError extends boolean = false>(options: Options<GetLineupStatsByGameData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetLineupStatsByGameResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/lineups/game/{gameId}',
        ...options
    });
};

/**
 * Returns betting lines for up to 3,000 games that match the filters, ordered by start date.
 */
export const getLines = <ThrowOnError extends boolean = false>(options?: Options<GetLinesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetLinesResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/lines',
        ...options
    });
};

/**
 * Returns available betting line providers.
 */
export const getProviders = <ThrowOnError extends boolean = false>(options?: Options<GetProvidersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetProvidersResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/lines/providers',
        ...options
    });
};

/**
 * Returns up to 3,000 games that match the filters, ordered by start date.
 */
export const getGames = <ThrowOnError extends boolean = false>(options?: Options<GetGamesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetGamesResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/games',
        ...options
    });
};

/**
 * Returns broadcast records for up to 3,000 games that match the filters, ordered by start date.
 */
export const getBroadcasts = <ThrowOnError extends boolean = false>(options?: Options<GetBroadcastsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetBroadcastsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/games/media',
        ...options
    });
};

/**
 * Returns team box scores and advanced metrics for up to 3,000 games that match the filters, ordered by start date.
 */
export const getGameTeams = <ThrowOnError extends boolean = false>(options?: Options<GetGameTeamsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetGameTeamsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/games/teams',
        ...options
    });
};

/**
 * Returns player box scores and advanced metrics for up to 1,000 games that match the filters, ordered by start date.
 */
export const getGamePlayers = <ThrowOnError extends boolean = false>(options?: Options<GetGamePlayersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetGamePlayersResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/games/players',
        ...options
    });
};

/**
 * Returns live scoreboard data. This endpoint requires Patreon Tier 1 access or higher.
 */
export const getScoreboard = <ThrowOnError extends boolean = false>(options?: Options<GetScoreboardData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetScoreboardResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/scoreboard',
        ...options
    });
};

/**
 * Returns NBA teams represented in the draft data.
 */
export const getDraftTeams = <ThrowOnError extends boolean = false>(options?: Options<GetDraftTeamsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDraftTeamsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/draft/teams',
        ...options
    });
};

/**
 * Returns player positions represented in the draft data.
 */
export const getDraftPositions = <ThrowOnError extends boolean = false>(options?: Options<GetDraftPositionsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDraftPositionsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/draft/positions',
        ...options
    });
};

/**
 * Returns historical NBA draft picks.
 */
export const getDraftPicks = <ThrowOnError extends boolean = false>(options?: Options<GetDraftPicksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDraftPicksResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/draft/picks',
        ...options
    });
};

/**
 * Returns available conferences and their identifiers.
 */
export const getConferences = <ThrowOnError extends boolean = false>(options?: Options<GetConferencesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetConferencesResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/conferences',
        ...options
    });
};

/**
 * Returns historical conference membership records.
 */
export const getConferenceHistory = <ThrowOnError extends boolean = false>(options?: Options<GetConferenceHistoryData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetConferenceHistoryResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/conferences/history',
        ...options
    });
};